### ISSUE TITLE
removed fof and broke site

### ISSUE THREAD

**Issue by cybersalt** [akeeba/magiceraser#3]
I just ran magic eraser on a J3 site, part of my routine for getting sites read for migrations.

This time the site broke (500 FOF 3.0 is not installed) and upon investigation I found my client had Akeeba Ticket System 3.4.1 installed and active. In know that AKS is no longer in development, but I though you would like to know this happened as I know magic eraser does look for other extensions which are dependent on FOF 3.0.

I reinstalled FOF 3.x 3.7.4 from the Akeeba site and that fixed things up.

While I have you, "PLG_CONSOLE_AKEEBABACKUP 7.5.0.1 202012-14" survived magic eraser as well. it shows in the extension manager with an X where other extensions show if they are enabled or not. I have seen this before and usually just manually remove it.

Also surviving magic Eraser is "Akeeba Strapper revAA17947 2016-05-12"  That looks pretty old to me, but at the same time maybe it is supposed to remain?

And my apologies for asking questions here. I went to open a ticket on Akeeba but there is no magic eraser place to assing the ticket.

**Comment by nikosdion** [comment]
MagicEraser never looks for any extensions depending on FOF. It just tries to uninstall FOF. It's FOF's installation script which checks dependencies. However, if someone extracted the ATS package all those several years ago and did a Discover installation type, the dependencies were never recorded, therefore FOF believed there were no dependents. Remember that the lack of reliable dependency management was one of the reasons I have been saying Joomla's extensions installer sucks?

PLG_CONSOLE_AKEEBABACKUP is a bad record, caused by Joomla! 3 misinterpreting the Joomla! 4 plugin manifest. Check the plugins/console folder for any stray files, and remove them.

The Akeeba Strapper record is also a bad record. Check if there is a media/strapper folder. If there is, remove it.

Keep in mind that MagicEraser only removes things which exist, not phantom database records. Its goal is to remove old, rotting code which should have been thrown away years ago.
